name: Build Raven

on:
  push:
    branches:
      - release*
  pull_request:
    branches:
      - master
      - develop
      - release*
    paths-ignore:
      - 'docs/**'
      - 'roadmap/**'
      - 'static-builds/**'
      - 'whitepaper/**'
      - 'binaries/**'
      - 'contrib/**'

env:
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts
  AWS_S3_ENABLE: ${{ secrets.AWS_S3_ENABLE }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: [ 'windows', 'linux', 'linux-disable-wallet', 'osx', 'arm32v7', 'arm32v7-disable-wallet' ]

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${{ MATRIX.OS }}

    - name: Copy Build Dependencies
      run: ${SCRIPTS}/02-copy-build-dependencies.sh ${{ MATRIX.OS }} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }} ${{ GITHUB.REF }}

    - name: Add Dependencies to the System PATH
      run: ${SCRIPTS}/03-export-path.sh ${{ MATRIX.OS }} ${{ GITHUB.WORKSPACE }}

    - name: Build Config
      run: cd ${{ GITHUB.WORKSPACE }} && ./autogen.sh

    - name: Configure Build
      run: ${SCRIPTS}/04-configure-build.sh ${{ MATRIX.OS }} ${{ GITHUB.WORKSPACE }}

    - name: Build Raven
      run: make -j2

    - name: Check Binary Security
      run: ${SCRIPTS}/05-binary-checks.sh ${{ MATRIX.OS }} ${{ GITHUB.WORKSPACE }}

    - name: Package Up the Build
      run: ${SCRIPTS}/06-package.sh ${{ MATRIX.OS }} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }} ${{ GITHUB.REF }}
    
    - name: Upload Build to the Nightly Site
      if: env.AWS_S3_ENABLE == 'true'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: "${{ GITHUB.WORKSPACE }}/release/"
        DEST_DIR: "${{ secrets.AWS_S3_LOCATION }}/${{ MATRIX.OS }}/"
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload Artifacts to Job
      uses: actions/upload-artifact@master
      with:
        name: ${{ MATRIX.OS }}
        path: ${{ GITHUB.WORKSPACE }}/release
